# Generated by Django 3.0.7 on 2020-06-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200622_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/main_app/static/images/avatar.jpg', upload_to='images/profile_pics'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
