# Generated by Django 3.0.7 on 2020-06-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200622_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/avatar.jpg', upload_to='images/profile_pics'),
        ),
    ]
